
-- Almacenes
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-GEN' limit 1 ), NULL, NULL, 'ALM-CENTRAL', 'Almacen Central', 'Almacen central total', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-CBBA', 'Almacen Cochabamba', 'Almacen regional para todo Cochabamba', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-CBBA-MIN', 'Almacen pequeño Cochabamba', 'Almacen para minoristas en Cochabamba', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-CONV' limit 1 ), NULL, NULL, 'ALM-ZONA-N', 'Almacen en la zona Norte', 'Almacen en Cochabamba para la zona Norte', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-CONV' limit 1 ), NULL, NULL, 'ALM-ZONA-S', 'Almacen en la zona Sur', 'Almacen en Cochabamba para la zona Sur', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-LP', 'Almacen La Paz', 'Almacen regional para todo La Paz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-LP-MIN', 'Almacen pequeño La Paz', 'Almacen para minoristas en La Paz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-TRA' limit 1 ), NULL, NULL, 'ALM-EA', 'Almacen El Alto - La Paz', 'Almacen regional para Alto - La Paz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-SCZ', 'Almacen Santa Cruz', 'Almacen regional para todo Santa Cruz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-REG' limit 1 ), NULL, NULL, 'ALM-SCZ-MIN', 'Almacen pequeño Santa Cruz', 'Almacen para minoristas en Santa Cruz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-COM' limit 1 ), NULL, NULL, 'ALM-COM', 'Almacen de combustibles en Santa Cruz', 'Almacen para combustibles en Santa Cruz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-MED' limit 1 ), NULL, NULL, 'ALM-MED', 'Almacen de medicamentos en Santa Cruz', 'Almacen de medicamentos en Santa Cruz', NULL, NULL);
INSERT INTO public.storehouse (active, storehouse_type_id, created_date, last_modified_date, code, "name", description, created_by, last_modified_by) VALUES(true, (select id from public.storehouse_type where code='TIPO-FRIG' limit 1 ), NULL, NULL, 'ALM-FRI', 'Almacen de frigorificos en Santa Cruz', 'Almacen de frigorificos en Santa Cruz', NULL, NULL);
