
-- Stock de productos con los que inicializara
INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-001' limit 1), true, (select id from storehouse where code='ALM-CBBA' limit 1), NULL, NULL, NULL, NULL);
INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-002' limit 1), true, (select id from storehouse where code='ALM-CBBA' limit 1), NULL, NULL, NULL, NULL);
--INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-003' limit 1), true, (select id from storehouse where code='ALM-CBBA' limit 1), NULL, NULL, NULL, NULL);
--INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-004' limit 1), true, (select id from storehouse where code='ALM-CBBA' limit 1), NULL, NULL, NULL, NULL);

INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-001' limit 1), true, (select id from storehouse where code='ALM-CENTRAL' limit 1), NULL, NULL, NULL, NULL);
INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-002' limit 1), true, (select id from storehouse where code='ALM-CENTRAL' limit 1), NULL, NULL, NULL, NULL);
--INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-003' limit 1), true, (select id from storehouse where code='ALM-CENTRAL' limit 1), NULL, NULL, NULL, NULL);
--INSERT INTO stock (active, quantity_in_stock, maximum_stock, minimum_stock, product_id, stock_alert, storehouse_id, created_date, last_modified_date, created_by, last_modified_by) VALUES(true, 5000.0, 500000.0, 1.0, (select id from product where code='A-004' limit 1), true, (select id from storehouse where code='ALM-CENTRAL' limit 1), NULL, NULL, NULL, NULL);
